version: '3.4'

services:
  crawler.service:
    image: ${DOCKER_REGISTRY-}crawlerservice
    build:
      context: .
      dockerfile: Crawler.Service/Dockerfile
    environment:
      MongoDB__Host: mongo
      TELEGRAM_API_TOKEN: 12345
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: crawler
      MONGO_INITDB_ROOT_PASSWORD: crawlerPassword
    volumes:
        - /docker/crawler/mongo:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 12000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: crawler
      ME_CONFIG_MONGODB_ADMINPASSWORD: crawlerPassword
    depends_on:
      - mongo