version: '3.4'

services:
  crawler.service:
    image: ${DOCKER_REGISTRY-}crawlerservice
    build:
      context: .
      dockerfile: Crawler.Service/Dockerfile
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: crawler
      MONGO_INITDB_ROOT_PASSWORD: crawlerPassword

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 12000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: crawler
      ME_CONFIG_MONGODB_ADMINPASSWORD: crawlerPassword