version: '3.4'

services:
  crawler.service:
    image: ${DOCKER_REGISTRY-}crawlerservice
    build:
      context: .
      dockerfile: src/PropertyBot.Service/Dockerfile
    environment:
      PROPERTY_POLLING_INTERVAL_IN_SECONDS: 60
      TELEGRAM_API_TOKEN: 12345
      
      MongoDB__Host: mongo
      MONGO_DB_USER: crawler
      MONGO_DB_PASSWORD: crawlerPassword
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: crawler
      MONGO_INITDB_ROOT_PASSWORD: crawlerPassword
    volumes:
        - /docker/crawler/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 12000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: crawler
      ME_CONFIG_MONGODB_ADMINPASSWORD: crawlerPassword
    depends_on:
      - mongo