name: Publish Docker Image

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore PropertyBot.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore PropertyBot.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal PropertyBot.sln
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: liofly/property-bot
        dockerfile: PropertyBot.Service/Dockerfile
        tag_with_ref: true
        tags: latest
